do not hardcode anymore inventory in ansible.cfg
Change-Id: I0153ae7a604cee3e8b3e42afdbe8b4b16ccc2ca3
Test-Hints: no-check

diff --git a/dci-openshift-app-agent-ctl b/dci-openshift-app-agent-ctl
--- a/dci-openshift-app-agent-ctl
+++ b/dci-openshift-app-agent-ctl
@@ -99,25 +99,31 @@ do
     esac
 done
 
-if [ -r ${config_dir}/hosts ] && [ -z "$prefix" ] ; then
-    hosts_args="-i ${config_dir}/hosts"
-fi
-
 if [ -n "$prefix" ]; then
-    hosts="$config_dir/${prefix}-hosts"
     settings="$config_dir/${prefix}-settings.yml"
     if [ -e "$settings" ]; then
-        prefix_args="${prefix_args} -e @$settings"
+        settings_args="-e @$settings"
     else
         echo "Missing $settings, will only use $config."
+        settings_args="-e @$config"
     fi
 
+    hosts="$config_dir/${prefix}-hosts"
     if [ -e "$hosts" ]; then
-        prefix_args="-i $hosts"
+        hosts_args="-i $hosts"
     else
-        echo "Missing $hosts"
-        exit 1
+        if [ -r "${config_dir}/hosts" ]; then
+            hosts_args="-i ${config_dir}/hosts"
+        else
+            echo "Missing $hosts or ${config_dir}/hosts"
+            exit 1
+        fi
     fi
+else
+    if [ -r ${config_dir}/hosts ]; then
+        hosts_args="-i ${config_dir}/hosts"
+    fi
+    settings_args="-e @$config"
 fi
 
 if [ "$start" != 1 ]; then
@@ -134,6 +140,6 @@ else
     export ANSIBLE_CONFIG=$DIR/dev-ansible.cfg
 fi
 
-exec ansible-playbook $extra_args dci-openshift-app-agent.yml -e @$config ${prefix_args} ${hosts_args} "$@"
+exec ansible-playbook $extra_args dci-openshift-app-agent.yml ${settings_args} ${hosts_args} "$@"
 
 # dci-openshift-app-agent-ctl ends here
