do not hardcode anymore inventory in ansible.cfg
Change-Id: I0153ae7a604cee3e8b3e42afdbe8b4b16ccc2ca3

diff --git a/dci-openshift-app-agent-ctl b/dci-openshift-app-agent-ctl
--- a/dci-openshift-app-agent-ctl
+++ b/dci-openshift-app-agent-ctl
@@ -115,8 +115,12 @@ if [ -n "$prefix" ]; then
     if [ -e "$hosts" ]; then
         prefix_args="-i $hosts"
     else
-        echo "Missing $hosts"
-        exit 1
+        if [ -r "${config_dir}/hosts" ]; then
+            prefix_args="-i ${config_dir}/hosts"
+        else
+            echo "Missing $hosts or ${config_dir}/hosts"
+            exit 1
+        fi
     fi
 fi
 
