Use OCP clients according to cluster version and from cache
- Currently if the OCP clients are already present on the jumphost those will be used
- Client version and server version may mistmatch
- The app agent overrides the clients installed on the server, so polluting the partner environment
- Will use the binaries in the agent's cache if present
- Facts for binary clients to be used on hooks

Change-Id: Ida1e1d53cd81565cf6367cd4eafe0efe51febe09

diff --git a/plays/scripts/get-logs b/plays/scripts/get-logs
--- a/plays/scripts/get-logs
+++ b/plays/scripts/get-logs
@@ -14,12 +14,26 @@
 # License for the specific language governing permissions and limitations
 # under the License.
 
+# Setting OC binary
+
 log=$1
 dir="$2"
 
 if [ $# -ne 2 ]; then
     echo "Usage: $0 <provisioner login> <dest dir>" 1>&2
     exit 1
+fi
+
+if [ -n "${3}" ]; then
+ oc_tool_path=${3};
+else
+  if ! command -v oc &> /dev/null
+  then
+      echo "oc could not be found"
+      exit
+  else
+      oc_tool_path=$(command -v oc)
+  fi
 fi
 
 rem="timeout -v 20m ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR $log"
@@ -38,18 +52,18 @@ remdir=$($rem mktemp -d)
 if [ -n "$remdir" ]; then
 
     # Get the output of various oc commands
-    $rem oc version > $dir/version.txt
-    $rem oc get clusterversion/version > $dir/clusterversion.txt
-    $rem oc get clusteroperator > $dir/clusteroperator.txt
-    $rem oc get network cluster -o yaml > $dir/clusternetwork.yaml
-    $rem oc get nodes -o wide > $dir/nodes.txt
-    $rem oc get nodes -o yaml > $dir/all-nodes.yaml
-    $rem oc get events --all-namespaces --sort-by='.metadata.creationTimestamp' > $dir/events.txt
-    $rem oc get pods --all-namespaces -o wide > $dir/pods.txt
+    $rem ${oc_tool_path} version > $dir/version.txt
+    $rem ${oc_tool_path} get clusterversion/version > $dir/clusterversion.txt
+    $rem ${oc_tool_path} get clusteroperator > $dir/clusteroperator.txt
+    $rem ${oc_tool_path} get network cluster -o yaml > $dir/clusternetwork.yaml
+    $rem ${oc_tool_path} get nodes -o wide > $dir/nodes.txt
+    $rem ${oc_tool_path} get nodes -o yaml > $dir/all-nodes.yaml
+    $rem ${oc_tool_path} get events --all-namespaces --sort-by='.metadata.creationTimestamp' > $dir/events.txt
+    $rem ${oc_tool_path} get pods --all-namespaces -o wide > $dir/pods.txt
 
     # must-gather
     # When a policy is defined, use the same mirror (local registry)
-    registry=$($rem oc get imageContentSourcePolicy image-policy-0 -o json 2>/dev/null |
+    registry=$($rem ${oc_tool_path} get imageContentSourcePolicy image-policy-0 -o json 2>/dev/null |
                         jq -r '.spec.repositoryDigestMirrors[].mirrors[]' |
                         grep -Pom1 '(\w+[.:])+\d+')
     for image in ${DCI_MUST_GATHER_IMAGES:-"registry.redhat.io/openshift4/ose-must-gather"}
@@ -64,7 +78,7 @@ if [ -n "$remdir" ]; then
 
     must_gather_dir="${remdir}/must_gather"
     $rem mkdir "${must_gather_dir}"
-    $rem oc adm must-gather \
+    $rem ${oc_tool_path} adm must-gather \
          --dest-dir=${must_gather_dir} \
          ${must_gather_opts}
 
